### PR TITLE
Use tokens to authorize workspace screenshots

### LINKED ISSUE #152: Screenshot plugin can't read annotations
> [mise/prod] CanCan::AccessDenied: You are not authorized to access this page.

The token authentication context is not passed through when requesting annotot annotations.

## Backtrace

    line 12 of [PROJECT_ROOT]/app/controllers/annotations_controller.rb: load_and_authorize_project
    line 16 of [PROJECT_ROOT]/app/controllers/annotations_controller.rb: load_annotations

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/84568/faults/79102315)

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #152

### CODE REVIEW

File: app/jobs/screenshot_workspace_job.rb [hunk 1]
```diff
@@ -18,17 +21,17 @@ def perform(workspace, timestamp = nil)
...
-      'HS256'
-    )
+  private
 
-    Rails.application.routes.url_helpers.url_for(
-      { action: 'embed', controller: 'workspaces', id: workspace.to_param, token: secret, timestamp: timestamp }
-        .merge(Settings.screenshot_url_parameters.to_h)
-    )
+  def token
+    JWT.encode({ exp: 5.minutes.from_now.to_i },
```
Comment (cbeer) [inline app/jobs/screenshot_workspace_job.rb:29]: If we continue to include the workspace in this token, we can use that data over in Ability to restrict access to just that workspace/project (instead of just letting a token-bearing user read anything they want 🤷 )

File: app/controllers/annotations_controller.rb [hunk 2]
```diff
@@ -2,23 +2,14 @@
 
 # Generic resources controller
 class AnnotationsController < Annotot::AnnotationsController
-  before_action :load_and_authorize_project
+  prepend_before_action :load_and_authorize_project
```
Comment (mjgiarlo) [inline app/controllers/annotations_controller.rb:5]: This is needed to run the filter before `Annotot::AnnotationsController` runs its filters. I believe beforehand, this was a no-op, which is why `load_and_authorize_project` needed to be hard-coded into the methods below.

File: app/controllers/concerns/token_ability.rb [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  end
+
+  def current_token
+    return unless token_from_authorization_header
+
+    payload, _header = JWT.decode(token_from_authorization_header,
+                                  Rails.application.secret_key_base,
+                                  'HS256')
+
+    HashWithIndifferentAccess.new(payload)
```
Comment (mjgiarlo) [inline app/controllers/concerns/token_ability.rb:16]: Prevent us from heartache later.

File: app/jobs/screenshot_workspace_job.rb (hunk 1 above)
Comment (mjgiarlo) [reply app/jobs/screenshot_workspace_job.rb:29]: I thought about that, and I also thought, "no real users have tokens, just puppeteers." Perhaps that is short-sighted.

**Review by cbeer — APPROVED** [review]

**Review by camillevilla — APPROVED** [review]
Neato. Checked this out locally and it's nice to see annotations showing up in workspace screenshots now ✨ 
Workspaces screenshots with annotations displayed
